### ISSUE TITLE
Update CIP-6 to accurately reflect the current state of implementation

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/CIPs#112]
## Description

CIP-6 was implemented and merged view pr: https://github.com/celestiaorg/celestia-app/pull/3094/files#diff-008f85e59c1e0f88e9ad4be82fd1a15f29261f9b9d1a71a19488c58b94fef363R200

`cip-6.md` [reference implementation](https://github.com/celestiaorg/CIPs/blob/main/cips/cip-6.md#reference-implementation) should be updated to reflect the changes.

**Comment by ninabarbakadze** [comment]
yes the reference implementation section. I'll update the issue to reflect that. @rootulp

**Comment by cmwaters** [comment]
Are we also able to move it into Final? I'll take one last pass to make sure everything is covered.

**Comment by rootulp** [comment]
FYI @ninabarbakadze https://github.com/celestiaorg/CIPs/pull/121 merged but didn't close this issue. I think because the hyphen in the PR description.
