### ISSUE TITLE
Consider havng squash and merge rule for Pull Requests

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/CIPs#117]
Currently, all commits in the PR are merged into the main, which is often dirty. I propose to enforce squashing so that each PS produces one clean cumulative commit of all the changes in the PR

**Comment by rootulp** [comment]
The current rules are in screenshot below. Is the request to disable merge commits? celestia-app enables squash and rebase merging and disables merge commits. 


## Screenshot 
<img width="791" alt="Screenshot 2024-03-27 at 4 03 19 PM" src="https://github.com/celestiaorg/CIPs/assets/3699047/9de16759-2a91-4922-8928-6d64984181ae">

**Comment by rootulp** [comment]
I updated the settings to reflect the screenshot below. Please re-open if you want something different @Wondertan 

## Screenshot

![Screenshot 2024-05-12 at 8 22 57 PM](https://github.com/celestiaorg/CIPs/assets/3699047/52bee64a-754d-456b-a52f-e0f758b46d32)
